### ISSUE TITLE
Permissions Issues

### ISSUE THREAD

**Issue by fchorney** [diracdeltas/demucs4max#5]
Hi, I got this installed and working in my Ableton 11, but I notice it doesn't seem to work when I try run it against a consolidated file on a non saved project. I get
```
node.script: Error: Command failed: demucs -n mdx_extra_q "D:/Music Production Software/Ableton/Live Recordings/2022-08-28 142824 Temp Project/Samples/Processed/Consolidate/Original Track [2022-08-28 151411].wav"
Traceback (most recent call last):
  File "C:\Users\liqui\AppData\Roaming\Python\Python39\Scripts\demucs-script.py", line 33, in <module>
    sys.exit(load_entry_point('demucs==3.0.4', 'console_scripts', 'demucs')())
  File "C:\Users\liqui\AppData\Roaming\Python\Python39\site-packages\demucs\separate.py", line 134, in main
    wav = load_track(track, model.audio_channels, model.samplerate)
  File "C:\Users\liqui\AppData\Roaming\Python\Python39\site-packages\demucs\separate.py", line 26, in load_track
    wav = AudioFile(track).read(
  File "C:\Users\liqui\AppData\Roaming\Python\Python39\site-packages\demucs\audio.py", line 101, in read
    streams = np.array(range(len(self)))[streams]
  File "C:\Users\liqui\AppData\Roaming\Python\Python39\site-packages\demucs\audio.py", line 62, in __len__
    return len(self._audio_streams)
  File "C:\Users\liqui\AppData\Roaming\Python\Python39\site-packages\demucs\audio.py", line 57, in _audio_streams
    index for index, stream in enumerate(self.info["streams"])
KeyError: 'streams'
```

I assume for some reason it doesn't have permissions to run on that wav file for some reason. Any idea on what I could do to fix it? Thanks!

**Comment by diracdeltas** [comment]
what happens if you just open Terminal (or cmd.exe/powershell on windows) and run `demucs -n mdx_extra_q "D:/Music Production Software/Ableton/Live Recordings/2022-08-28 142824 Temp Project/Samples/Processed/Consolidate/Original Track [2022-08-28 151411].wav"`?

**Comment by fchorney** [comment]
I end up getting the same thing, regardless if I run CMD with admin or not. Seems like for some reason something can't run on that file. `ffproc` maybe? As it looks like it can't grab the audio streams it needs is my guess.
